#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#


#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
kind: Secret
metadata:
  name: testsecret
data:
  test_password: dGVzdHBhc3N3b3Jk